### PR TITLE
Fix for #10

### PR DESCRIPTION
**Pull request by jarpi**
Added a linter
- It scans 'index.js', 'src/*', 'spec/*'
- Modified code in order to get rid of linter errors
- Changed ws server instantiation from constructor pattern to OLOO

### CODE REVIEW

**Comment by brucelane** [comment]
why did you remove nodemon for production?

**Comment by jarpi** [comment]
Think it's a feature we use while developing, but in production we don't care. Do you want it back?

**Comment by jarpi** [comment]
Also think, we need code reviews. If there exists questions about the PR, then, don't merge the PR until all are solved. 
It's good to discuss changes, think about them and fix if it's necessary. :)
Even more, we should review every PR before merging in any repo.

**Comment by brucelane** [comment]
I knew that would come up, the "don't merge PR until solved" and you're right.
Should I clone your fork to test your PR or there is a better way?

**Comment by jarpi** [comment]
You could get only the [PR in your local](https://help.github.com/articles/checking-out-pull-requests-locally/)

**Pull request merged**
